"""Test-suite bootstrap.

Runs before conftest, because pytest imports this package first.

Secrets here are ephemeral and in-memory: they authenticate nothing, are never
written to disk, and exist so the suite does not depend on a developer's `.env`.
The values that matter — GitHub's webhook secret (H-003) and the internal API
token (H-004) — belong to the human and are never generated by the build.
"""

import os
import secrets

os.environ.setdefault("GITHUB_WEBHOOK_SECRET", secrets.token_hex(32))
os.environ.setdefault("INTERNAL_API_TOKEN", secrets.token_hex(32))
