"""Test-suite bootstrap.

Runs before conftest, because pytest imports this package first.

Secrets here are ephemeral and in-memory: they authenticate nothing, are never
written to disk, and exist so the suite does not depend on a developer's `.env`.
The real values — GitHub's webhook secret and the internal API token — are
operator-supplied and never generated by the build.
"""

import os
import secrets

os.environ.setdefault("GITHUB_WEBHOOK_SECRET", secrets.token_hex(32))
os.environ.setdefault("INTERNAL_API_TOKEN", secrets.token_hex(32))

from app.config import Settings  # noqa: E402  (must follow the environment above)

# Cut the suite off from the developer's `.env`.
#
# Hermeticity here was luck until `.env` gained the App id and a path to a real
# private key: a test asserting that a missing credential raises began passing or
# failing depending on whose machine it ran on. A test must never read a real
# secret, and "needs no .env" has to be enforced rather than assumed. The database
# URL's default already matches what `.env` sets, so local Postgres is still found.
Settings.model_config["env_file"] = None
